	//JavaScript
	
	
	//点击主题导航，跳转页面
	function click1(){
		window.open("#");
	}
	function click2(){
		window.open("#");
	}
	function click3(){
		window.open("#");
	}
	function click4(){
		window.open("#");
	}
	function click5(){
		window.open("#");
	}
	function click6(){
		window.open("#");
	}
	function click7(){
		window.open("#");
	}
	function click8(){
		window.open("#");
	}
	//点击立即购买跳转页面
	function buy1(){
		window.open("#");
	}
	function buy2(){
		window.open("#");
	}
	function buy3(){
		window.open("#");
	}
	function buy4(){
		window.open("#");
	}
	function buy5(){
		window.open("#");
	}
	//点击展示图片跳转页面
	function linkimg0(){
		window.open("#");
	}
	function linkimg1(){
		window.open("#");
	}
	function linkimg2(){
		window.open("#");
	}
	function linkimg3(){
		window.open("#");
	}
	function linkimg4(){
		window.open("#");
	}
	function linkimg5(){
		window.open("#");
	}
	//jQuery
	//导航栏移动到文字上文字变化
			$(function(){
				$(".li-header-navi").mouseover(function(){
					$(".li-header-navi:hover").css("color","white");
				});
				$(".li-header-navi").mouseout(function(){
					$(".li-header-navi").css("color","#B0B0B0");
				});
			});
			//搜索图标的切换
			$(function(){
				$("#sumbit").mouseover(function(){
					$("#sumbit").css("background","url(img/搜索可点击.png)");
					$("#sumbit").css("cursor","pointer");
					$("#search").css("border-color","black");
				});
				$("#sumbit").mouseout(function(){
					$("#sumbit").css("background","url(img/搜索icon.png)");
					$("#search").css("border-color","darkgray");
				});
			});
			//购物车
			$(function(){
				$("#header-down-shopCar").mouseover(function(){
					$("#header-down-shopCar").css("background","url(img/购物车点击.png)");
					$("#shopcar").slideToggle("fast",function(){
						
					});
				});	
				$("#header-down-shopCar").mouseout(function(){
					$("#header-down-shopCar").css("background","url(img/购物车未点击.png)");
					$("#shopcar").slideToggle("fast",function(){
						
					});
				});
				
			});
			//第二导航文字
			$(function(){
				$(".li-main-navigation").mouseover(function(){
					$(".li-main-navigation:hover").css("color","#FF6700");
					$(".li-main-navigation:hover").css("color","#FF6700");
				});
				$("li").mouseout(function(){
					$(".li-main-navigation").css("color","black");
					$(".li-main-navigation:hover").css("color","#FF6700");
				});
			});
			//导航栏下滑效果
			$(function(){
				$("#li1").mouseover(function(){
					$("#nav-slide-down1").stop(true,false).slideDown();
					});
				$("#li1").mouseout(function(){
						$("#nav-slide-down1").stop(true,false).slideUp();
					});
				});
				$(function(){
				$("#li2").mouseover(function(){
					$("#nav-slide-down2").stop(true,false).slideDown();
					});
				$("#li2").mouseout(function(){
						$("#nav-slide-down2").stop(true,false).slideUp();
					});
				});
				$(function(){
				$("#li3").mouseover(function(){
					$("#nav-slide-down3").stop(true,false).slideDown();
					});
				$("#li3").mouseout(function(){
						$("#nav-slide-down3").stop(true,false).slideUp();
					});
				});
				$(function(){
				$("#li4").mouseover(function(){
					$("#nav-slide-down4").stop(true,false).slideDown();
					});
				$("#li4").mouseout(function(){
						$("#nav-slide-down4").stop(true,false).slideUp();
					});
				});
				$(function(){
				$("#li5").mouseover(function(){
					$("#nav-slide-down5").stop(true,false).slideDown();
					});
				$("#li5").mouseout(function(){
						$("#nav-slide-down5").stop(true,false).slideUp();
					});
				});
			
			//固定下滑栏
			$(function(){
				$("#nav-slide-down1").mouseover(function(){
					$("#nav-slide-down1").stop(true,false).slideDown();
				});
				$("#nav-slide-down1").mouseout(function(){
					$("#nav-slide-down1").stop(true,false).slideUp();
				});
			});
			$(function(){
				$("#nav-slide-down2").mouseover(function(){
					$("#nav-slide-down2").stop(true,false).slideDown();
				});
				$("#nav-slide-down2").mouseout(function(){
					$("#nav-slide-down2").stop(true,false).slideUp();
				});
			});
			$(function(){
				$("#nav-slide-down3").mouseover(function(){
					$("#nav-slide-down3").stop(true,false).slideDown();
				});
				$("#nav-slide-down3").mouseout(function(){
					$("#nav-slide-down3").stop(true,false).slideUp();
				});
			});
			$(function(){
				$("#nav-slide-down4").mouseover(function(){
					$("#nav-slide-down4").stop(true,false).slideDown();
				});
				$("#nav-slide-down4").mouseout(function(){
					$("#nav-slide-down4").stop(true,false).slideUp();
				});
			});
			$(function(){
				$("#nav-slide-down5").mouseover(function(){
					$("#nav-slide-down5").stop(true,false).slideDown();
				});
				$("#nav-slide-down5").mouseout(function(){
					$("#nav-slide-down5").stop(true,false).slideUp();
				});
			});
	$(function(){
		//鼠标放置文本“首页”上字体变色
		$("a").mouseover(function(){
			$("a").css("color","black");
		});
		$("a").mouseout(function(){
			$("a").css("color","#757575");
		});
		//鼠标移入主体导航变色并变为小手形状
		$("#ulmain-list1").mouseover(function(){
			$("#ulmain-list1").css("cursor","pointer");
			$("#ulmain-list1").css("color","#FF6700");
		});
		$("#ulmain-list1").mouseout(function(){
			$("#ulmain-list1").css("color","#757575");
		});
		$("#ulmain-list2").mouseover(function(){
			$("#ulmain-list2").css("cursor","pointer");
			$("#ulmain-list2").css("color","#FF6700");
		});
		$("#ulmain-list2").mouseout(function(){
			$("#ulmain-list2").css("color","#757575");
		});
		$("#ulmain-list3").mouseover(function(){
			$("#ulmain-list3").css("cursor","pointer");
			$("#ulmain-list3").css("color","#FF6700");
		});
		$("#ulmain-list3").mouseout(function(){
			$("#ulmain-list3").css("color","#757575");
		});
		$("#ulmain-list4").mouseover(function(){
			$("#ulmain-list4").css("cursor","pointer");
			$("#ulmain-list4").css("color","#FF6700");
		});
		$("#ulmain-list4").mouseout(function(){
			$("#ulmain-list4").css("color","#757575");
		});
		$("#ulmain-list5").mouseover(function(){
			$("#ulmain-list5").css("cursor","pointer");
			$("#ulmain-list5").css("color","#FF6700");
		});
		$("#ulmain-list5").mouseout(function(){
			$("#ulmain-list5").css("color","#757575");
		});
		$("#ulmain-list6").mouseover(function(){
			$("#ulmain-list6").css("cursor","pointer");
			$("#ulmain-list6").css("color","#FF6700");
		});
		$("#ulmain-list6").mouseout(function(){
			$("#ulmain-list6").css("color","#757575");
		});
		$("#ulmain-list7").mouseover(function(){
			$("#ulmain-list7").css("cursor","pointer");
			$("#ulmain-list7").css("color","#FF6700");
		});
		$("#ulmain-list7").mouseout(function(){
			$("#ulmain-list7").css("color","#757575");
		});
		
		$("#ulmain-list8").mouseover(function(){
			$("#ulmain-list8").css("cursor","pointer");
		});
	});
	//鼠标放置立即购买上时字体和背景的变化
	$(function(){
		$("#mainbtn1").mouseover(function(){
			$("#mainbtn1").css("cursor","pointer");
			$("#mainbtn1").css("background","#FF6700");
			$("#btnspan1").css("color","white");
		});
		$("#mainbtn1").mouseout(function(){
			$("#mainbtn1").css("background","white");
			$("#btnspan1").css("color","#FF6700");
		});
		$("#mainbtn2").mouseover(function(){
			$("#mainbtn2").css("cursor","pointer");
			$("#mainbtn2").css("background","#FF6700");
			$("#btnspan2").css("color","white");
		});
		$("#mainbtn2").mouseout(function(){
			$("#mainbtn2").css("background","white");
			$("#btnspan2").css("color","#FF6700");
		});
		$("#mainbtn3").mouseover(function(){
			$("#mainbtn3").css("cursor","pointer");
			$("#mainbtn3").css("background","#FF6700");
			$("#btnspan3").css("color","white");
		});
		$("#mainbtn3").mouseout(function(){
			$("#mainbtn3").css("background","white");
			$("#btnspan3").css("color","#FF6700");
		});
		$("#mainbtn4").mouseover(function(){
			$("#mainbtn4").css("cursor","pointer");
			$("#mainbtn4").css("background","#FF6700");
			$("#btnspan4").css("color","white");
		});
		$("#mainbtn4").mouseout(function(){
			$("#mainbtn4").css("background","white");
			$("#btnspan4").css("color","#FF6700");
		});
		$("#mainbtn5").mouseover(function(){
			$("#mainbtn5").css("cursor","pointer");
			$("#mainbtn5").css("background","#FF6700");
			$("#btnspan5").css("color","white");
		});
		$("#mainbtn5").mouseout(function(){
			$("#mainbtn5").css("background","white");
			$("#btnspan5").css("color","#FF6700");
		});
	});
	//鼠标放置到展示图片时鼠标呈小手状态
	$(function(){
		$("#mainimg1").mouseover(function(){
			$("#mainimg1").css("cursor","pointer")
		});
		$("#link-img1").mouseover(function(){
			$("#link-img1").css("cursor","pointer")
		});
		$("#link-img2").mouseover(function(){
			$("#link-img2").css("cursor","pointer")
		});
		$("#link-img3").mouseover(function(){
			$("#link-img3").css("cursor","pointer")
		});
		$("#link-img4").mouseover(function(){
			$("#link-img4").css("cursor","pointer")
		});
		$("#link-img5").mouseover(function(){
			$("#link-img5").css("cursor","pointer")
		});
	});
	//后期
	$(function(){
		$(".bottom-li").mouseover(function(){
			$(".bottom-li:hover").css("color","#FF6700");
		});
		
			$(".bottom-li").mouseout(function(){
			$(".bottom-li").css("color","black");
		
		});
	});
	//24小时按钮
	$(function(){
		$("#btn").mouseover(function(){
			$("#btn").css("color","white");
			$("#btn").css("background","#FF6700");
		});
		
		$("#btn").mouseout(function(){
			$("#btn").css("color","#FF6700");
			$("#btn").css("background","white");
			
		});
	});