/* 鼠标单击四个界面相互换面字体换色*/
$(function(){
			$("#status-all").click(function(){
				$("#order-all").css("display","block");
				$("#status-all").css("color","#FF6700");
				$("#order-unpay").css("display","none");
				$("#status-unpay").css("color","black");
				$("#order-Send").css("display","none");
				$("#status-Send").css("color","black");
				$("#order-noSend").css("display","none");
				$("#status-noSend").css("color","black");
				$("#order-invalid").css("display","none");
				$("#status-invalid").css("color","black");
				
			});	
		});
		$(function(){
			$("#status-unpay").click(function(){
				$("#order-all").css("display","none");
				$("#status-all").css("color","black");
				$("#order-unpay").css("display","block");
				$("#status-unpay").css("color","#FF6700");
				$("#order-Send").css("display","none");
				$("#status-Send").css("color","black");
				$("#order-noSend").css("display","none");
				$("#status-noSend").css("color","black");
				$("#order-invalid").css("display","none");
				$("#status-invalid").css("color","black");
			});
		});
		$(function(){
			$("#status-Send").click(function(){
				$("#order-all").css("display","none");
				$("#status-all").css("color","black");
				$("#order-unpay").css("display","none");
				$("#status-unpay").css("color","black");
				$("#order-Send").css("display","block");
				$("#status-Send").css("color","#FF6700");
				$("#order-noSend").css("display","none");
				$("#status-noSend").css("color","black");
				$("#order-invalid").css("display","none");
				$("#status-invalid").css("color","black");
			});
		});
		$(function(){
			$("#status-noSend").click(function(){
				$("#order-all").css("display","none");
				$("#status-all").css("color","black");
				$("#order-unpay").css("display","none");
				$("#status-unpay").css("color","black");
				$("#order-Send").css("display","none");
				$("#status-Send").css("color","black");
				$("#order-noSend").css("display","block");
				$("#status-noSend").css("color","#FF6700");
				$("#order-invalid").css("display","none");
				$("#status-invalid").css("color","black");
			});
		});
			$(function(){
			$("#status-invalid").click(function(){
				$("#order-all").css("display","none");
				$("#status-all").css("color","black");
				$("#order-unpay").css("display","none");
				$("#status-unpay").css("color","black");
				$("#order-Send").css("display","none");
				$("#status-Send").css("color","black");
				$("#order-noSend").css("display","none");
				$("#status-noSend").css("color","black");
				$("#order-invalid").css("display","block");
				$("#status-invalid").css("color","#FF6700");
			});
		});
		
		
		
		
		/*鼠标移入搜索背景换色*/
		$(function(){
			$("#search-btn").mouseover(function(){
				$("#search-btn").css("background","url(../img/s-2.png)");
			});		
			$("#search-btn").mouseout(function(){
                $("#search-btn").css("background","url(../img/s-1.png)");
          	});
 		});
		/*鼠标移入订单详情变色*/
		$(function(){
			$("#details1").mouseover(function(){
				$("#details1").css("background","#757575");
				$("#details1").css("color","white");
			});		
			$("#details1").mouseout(function(){
                $("#details1").css("background","#FFFFFF");
                $("#details1").css("color","black");
         	});
			$("#details2").mouseover(function(){
				$("#details2").css("background","#757575");
				$("#details2").css("color","white");
			});		
			$("#details2").mouseout(function(){
                $("#details2").css("background","#FFFFFF");
                $("#details2").css("color","black");
          	});
			$("#details3").mouseover(function(){
				$("#details3").css("background","#757575");
				$("#details3").css("color","white");
			});		
			$("#details3").mouseout(function(){
                $("#details3").css("background","white");
                $("#details3").css("color","black");
          	});
			$("#details4").mouseover(function(){
				$("#details4").css("background","#757575");
				$("#details4").css("color","white");
			});		
			$("#details4").mouseout(function(){
                $("#details4").css("background","#FFFFFF");
                $("#details4").css("color","black");
          	});
          	$("#details5").mouseover(function(){
				$("#details5").css("background","#757575");
				$("#details5").css("color","white");
			});		
			$("#details5").mouseout(function(){
                $("#details5").css("background","#FFFFFF");
                $("#details5").css("color","black");
          	});
          	$("#details6").mouseover(function(){
				$("#details6").css("background","#757575");
				$("#details6").css("color","white");
			});		
			$("#details6").mouseout(function(){
                $("#details6").css("background","#FFFFFF");
                $("#details6").css("color","black");
          	});
 		});	
 		/*点击 小米5的订单详情后跳转订单详情页面*/
 		$(function(){
	 		$("#details1").click(function(){
	 			window.location.href="orderDetails.html";
	 		});
	 		$("#details5").click(function(){
	 			window.location.href="orderDetails.html";
	 		});
 		});
 		